/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author rostr
 */
public class LoginForm extends javax.swing.JFrame {

   PanelBackground background = new PanelBackground();
  public LoginForm() {
    this.setContentPane(background);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnExit = new javax.swing.JToggleButton();
    entryUsername = new javax.swing.JTextField();
    entryPassword = new javax.swing.JPasswordField();
    chckbxShowPassword = new javax.swing.JCheckBox();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(900, 600));
    setPreferredSize(new java.awt.Dimension(1600, 900));
    setResizable(false);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    btnExit.setBackground(new java.awt.Color(255, 153, 153));
    btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnExit.setText("Exit");
    btnExit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnExitActionPerformed(evt);
      }
    });
    getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 740, 140, 40));

    entryUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    entryUsername.setText("Username");
    entryUsername.setBorder(null);
    getContentPane().add(entryUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 650, 70));

    entryPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    entryPassword.setText("Password");
    entryPassword.setBorder(null);
    entryPassword.setPreferredSize(new java.awt.Dimension(108, 29));
    getContentPane().add(entryPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 650, 70));

    chckbxShowPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    chckbxShowPassword.setForeground(new java.awt.Color(255, 255, 255));
    chckbxShowPassword.setText("Show Password");
    chckbxShowPassword.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chckbxShowPasswordActionPerformed(evt);
      }
    });
    getContentPane().add(chckbxShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, 160, 30));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void chckbxShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxShowPasswordActionPerformed
    if (chckbxShowPassword.isSelected()) {
      entryPassword.setEchoChar((char)0);
    }
    else {
      entryPassword.setEchoChar('*');
    }
  }//GEN-LAST:event_chckbxShowPasswordActionPerformed

  private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
    System.exit(0);
  }//GEN-LAST:event_btnExitActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new LoginForm().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JToggleButton btnExit;
  private javax.swing.JCheckBox chckbxShowPassword;
  private javax.swing.JPasswordField entryPassword;
  private javax.swing.JTextField entryUsername;
  // End of variables declaration//GEN-END:variables
  
  /**
   * Class panelBackground.
   * Inner class that creates a background image to the window.
   */
  
  class PanelBackground extends JPanel {
    private Image backgroundImage;
    
    @Override
    public void paint(Graphics grph) {
      backgroundImage = new ImageIcon(getClass().getResource("/images/loginForm2.jpg")).getImage();
      grph.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
      setOpaque(false);
      
      super.paint(grph);
    }
  }
}