/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import Exception.BirthdateNullException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rostr
 */
public class RegisterForm extends javax.swing.JFrame {
  
  PanelBackground background = new PanelBackground();
  /**
   * Creates new form RegisterForm
   */
  public RegisterForm() {
    this.setContentPane(background);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    entrySecondName = new javax.swing.JTextField();
    entryFirstName = new javax.swing.JTextField();
    entrySecondLastname = new javax.swing.JTextField();
    entryFirstLastname = new javax.swing.JTextField();
    entryEmail = new javax.swing.JTextField();
    entryUsername = new javax.swing.JTextField();
    jButton2 = new javax.swing.JButton();
    jDateChooser1 = new com.toedter.calendar.JDateChooser();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setPreferredSize(new java.awt.Dimension(1920, 1080));
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jButton1.setBackground(new java.awt.Color(255, 102, 102));
    jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButton1.setText("Volver");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 780, 120, 30));

    entrySecondName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
    entrySecondName.setForeground(Color.LIGHT_GRAY);
    entrySecondName.setText("Segundo nombre (opcional)");
    getContentPane().add(entrySecondName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 280, 50));

    entryFirstName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
    entryFirstName.setForeground(Color.LIGHT_GRAY);
    entryFirstName.setText("Primer nombre");
    entryFirstName.setSelectedTextColor(new java.awt.Color(0, 0, 0));
    entryFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        entryFirstNameFocusGained(evt);
      }
      public void focusLost(java.awt.event.FocusEvent evt) {
        entryFirstNameFocusLost(evt);
      }
    });
    getContentPane().add(entryFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 280, 50));

    entrySecondLastname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
    entrySecondLastname.setForeground(Color.LIGHT_GRAY);
    entrySecondLastname.setText("Segundo apellido");
    getContentPane().add(entrySecondLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 280, 50));

    entryFirstLastname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
    entryFirstLastname.setForeground(Color.LIGHT_GRAY);
    entryFirstLastname.setText("Primer apellido");
    getContentPane().add(entryFirstLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 280, 50));

    entryEmail.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
    entryEmail.setForeground(Color.LIGHT_GRAY);
    entryEmail.setText("Correo");
    getContentPane().add(entryEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 280, 50));

    entryUsername.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
    entryUsername.setForeground(Color.LIGHT_GRAY);
    entryUsername.setText("Nombre de usuario");
    getContentPane().add(entryUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 280, 50));

    jButton2.setText("view date");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, -1, -1));
    getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 150, -1));

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Birthdate");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 120, 20));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    LoginForm lf = new LoginForm();
    lf.show();
    dispose();
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try {
    Date date = jDateChooser1.getDate();
    if (date == null) {
      throw new BirthdateNullException("You must select a valid birthdate!");
    }
    long d = date.getTime();
    java.sql.Date selectedDate = new java.sql.Date(d);
    JOptionPane.showMessageDialog(null, selectedDate);
    } catch(BirthdateNullException ex) {
      System.out.println(ex);
    }
  }//GEN-LAST:event_jButton2ActionPerformed

  private void entryFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entryFirstNameFocusGained
    entryFirstName.setText("");
    entryFirstName.setForeground(Color.DARK_GRAY);
  }//GEN-LAST:event_entryFirstNameFocusGained

  private void entryFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entryFirstNameFocusLost
    entryFirstName.setText("Primer nombre");
    entryFirstName.setForeground(Color.LIGHT_GRAY);
  }//GEN-LAST:event_entryFirstNameFocusLost

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new RegisterForm().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField entryEmail;
  private javax.swing.JTextField entryFirstLastname;
  private javax.swing.JTextField entryFirstName;
  private javax.swing.JTextField entrySecondLastname;
  private javax.swing.JTextField entrySecondName;
  private javax.swing.JTextField entryUsername;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private com.toedter.calendar.JDateChooser jDateChooser1;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
  
  /**
   * Class panelBackground.
   * Inner class that creates a background image to the window.
   */
  
  class PanelBackground extends JPanel {
    private Image backgroundImage;
    
    @Override
    public void paint(Graphics grph) {
      backgroundImage = new ImageIcon(getClass().getResource("/images/registerForm.jpg")).getImage();
      grph.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
      setOpaque(false);
      
      super.paint(grph);
    }
  }
}
